"""
This type stub file was generated by pyright.
"""

import sys
from qrcode.main import QRCode, make
from qrcode.constants import ERROR_CORRECT_H, ERROR_CORRECT_L, ERROR_CORRECT_M, ERROR_CORRECT_Q
from qrcode import image

def run_example(data=..., *args, **kwargs): # -> None:
    """
    Build an example QR Code and display it.

    There's an even easier way than the code here though: just use the ``make``
    shortcut.
    """
    ...

if __name__ == '__main__':
    ...
