"""
This type stub file was generated by pyright.
"""

import sys

"""
qr - Convert stdin (or the first argument) to a QR Code.

When stdout is a tty the QR Code is printed to the terminal and when stdout is
a pipe to a file an image is written. The default image format is PNG.
"""
if sys.platform.startswith(('win', 'cygwin')):
    ...
default_factories = ...
error_correction = ...
def main(args=...): # -> None:
    ...

if __name__ == "__main__":
    ...
