"""
This type stub file was generated by pyright.
"""

"""
This file provides zest.releaser entrypoints using when releasing new
qrcode versions.
"""
def update_manpage(data): # -> None:
    """
    Update the version in the manpage document.
    """
    ...

