"""
This type stub file was generated by pyright.
"""

import qrcode.image.base

class PilImage(qrcode.image.base.BaseImage):
    """
    PIL image builder, default format is PNG.
    """
    kind = ...
    def new_image(self, **kwargs): # -> Image:
        ...
    
    def drawrect(self, row, col): # -> None:
        ...
    
    def save(self, stream, format=..., **kwargs): # -> None:
        ...
    
    def __getattr__(self, name): # -> Any:
        ...
    


